#!/usr/bin/env bash

## TODO: Put bash notes in bash notes.

# Already running?
if [ $(./nf-status) -eq 1 ]; then
    echo 'Running'
    exit
fi

# Falcon Server
cd Server && poetry run ./start-server.sh &

# HeroUI Client
# Notes: The cd itself is backgrounded. We never leave here.
# cd - puts us back in Server.
# The team sent somebody there, and that's where the team was last.
# But we never left here.
cd Client && npm run dev &
#cd -
#pwd


# Supabase DB
# under construction!
