#!/usr/bin/bash

## TODO: Put bash notes in bash notes.

# Already running?
if [ $(./nf-status) -eq 1 ]; then
    echo 'Running'
    exit
fi

# Falcon Server
cd Server/Falcon-Uvicorn && poetry run ./start-server.sh &

# nginx serving HeroUI Client
cd Server/nginx && ./start.sh

