#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Usage: $0 'single-quote enclosed url'"
    exit
fi

agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"


yt-dlp --flat-playlist "$1" -J 2>/dev/null | jq -r '.entries[].url' | grep http
#    --user-agent "$agent" "$1" \
#    --referer "https://www.google.com" \
#    --no-check-certificate \
