#!/usr/bin/bash

# Destructively remove the first line of new-urls

# Dir in which this script resides
dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
#dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

sed -i '1d' $dir/new-urls

